sudo: false

language: python

python:
  - 3.6

stages:
    - test
    - name: deploy
      if: tag IS present

jobs:
  include:
    - stage: test
      install:
          - pip install .
          - pip install coverage codecov codacy-coverage pytest pytest-cov
      script:
          - pytest --cov

      after_success:
          - codecov
          - coverage report -m
          - export CODACY_PROJECT_TOKEN=f5e3e796439b4c5c9df4c5848b69cfd9
          - coverage xml
          - python-codacy-coverage -r coverage.xml

    # - stage: test_conda
    #   install:
    #       - echo "Installing using conda"
    #   script:
    #       - echo "Runing conda test"
      # after_sucess: skip
    - stage: deploy         # Deploy stage (only for tagged versions)
      #if: tag IS present
      # install: skip
      # after_success: skip
      script:
          - echo "Building docker container..."
      name: "Deploy Docker"

    - script:
          - echo "Builing conda package"
      name: "Deploy Conda"

# install:
#     - pip install .
#     - pip install coverage codecov codacy-coverage pytest pytest-cov
#
# script:
#     - pytest --cov
#
# after_success:
#     - codecov
#     - coverage report -m
#     - export CODACY_PROJECT_TOKEN=f5e3e796439b4c5c9df4c5848b69cfd9
#     - coverage xml
#     - python-codacy-coverage -r coverage.xml
