sudo: false

language: python

python:
  - 3.6

install:
  - pip install .
  - pip install coverage codecov codacy-coverage

before_script:
  - export PYTHONPATH=./src:$PYTHONPATH

script:
  - pytest

after_success:
  - codecov
  - coverage report -m
  - export CODACY_PROJECT_TOKEN=f5e3e796439b4c5c9df4c5848b69cfd9
  - coverage xml
  - python-codacy-coverage -r coverage.xml
