sudo: false

language: python

python:
  - 3.6

install:
  - pip install .
  - pip install coverage codecov codacy-coverage pytest pytest-cov

jobs:
  include:
    - stage: unit-tests
      script:
        - pytest --cov
        - codecov
        - coverage report -m
        - export CODACY_PROJECT_TOKEN=f5e3e796439b4c5c9df4c5848b69cfd9
        - coverage xml
        - python-codacy-coverage -r coverage.xml
    - stage: deploy
      if: branch = master
      script:
        - echo "Building container"

# script:
#   - pytest --cov
#
# after_success:
#   - codecov
#   - coverage report -m
#   - export CODACY_PROJECT_TOKEN=f5e3e796439b4c5c9df4c5848b69cfd9
#   - coverage xml
#   - python-codacy-coverage -r coverage.xml
