sudo: false

language: python

python:
  - 3.6

install:
  - pip install coverage codecov codacy-coverage
  - mkdir packages; cd packages
  - sudo wget -O boost_1_64_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.gz/download
  - sudo tar xzf boost_1_64_0.tar.gz
  - cd boost_1_64_0/
  - sudo ./bootstrap.sh --prefix=/usr/local
  - sudo ./b2
  - sudo ./b2 install -d0
  - cd ../..
  # - sudo apt-get install libboost-all-dev

script:
  - coverage run test.py

after_success:
  - codecov
  - coverage report -m
  - export CODACY_PROJECT_TOKEN=f5e3e796439b4c5c9df4c5848b69cfd9
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - cat /usr/local/boost/version.hpp | grep "BOOST_LIB_VERSION"
  - Python3 -V
