# This workflow will enforce PR to have at least one of the mandatory labels

name: EnforcePRLabel
on: [pull_request]

jobs:
  enforce-pr-label:

    runs-on: ubuntu-latest

    steps:
    - name: Enforce PR label
      uses: yogevbd/enforce-label-action@1.0.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        VALID_LABELS: "bug,enhancement,feature"
